services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-256
      - KAFKA_CLIENT_USERS=orderuser
      - KAFKA_CLIENT_PASSWORDS=order123
      - KAFKA_INTER_BROKER_USER=orderuser
      - KAFKA_INTER_BROKER_PASSWORD=order123
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    command: >
      bash -c "
        /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh &
        sleep 20
        kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9093 --topic orders-topic --replication-factor 1 --partitions 1 --command-config /opt/bitnami/kafka/config/producer.properties
        kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9093 --topic orders-topic-dlq --replication-factor 1 --partitions 1 --command-config /opt/bitnami/kafka/config/producer.properties
        kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9093 --topic orders-topic-retry --replication-factor 1 --partitions 1 --command-config /opt/bitnami/kafka/config/producer.properties
        wait
      "
    volumes:
      - ./kafka/producer.properties:/opt/bitnami/kafka/config/producer.properties

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="orderuser" password="order123";

  api-mock:
    build:
      context: ./api_mock
    ports:
      - "8080:3000"
    environment:
      - MOCK_SHOULD_FAIL=false
